# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bikereview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('review', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikemodels', to='bikes.bikemake')),
            ],
        ),
        migrations.RemoveField(
            model_name='bikemodel',
            name='make',
        ),
        migrations.DeleteModel(
            name='bikemodel',
        ),
    ]
