# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20170624_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikereview',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BikeModels', to='bikes.BikeMake'),
        ),
    ]
